spring.application.name=SIEC-API
jwt.secret=hP1qGZxRKMkGZybREsD8OeOdu3+2VkxulIxtYfP3yBfXH4XylqskvXQssZrE7CGq3xtjQ3iMv0tXnkaITKxZaw==

spring.datasource.url=jdbc:mysql://localhost:3306/SIEC
spring.datasource.username=root
spring.datasource.password=root

# Configuraci?n de Hibernate (JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
